name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Check Node Version
        run: node -v && npm -v

      - name: Install and Build
        run: npm install && npm run build
        env:
          REACT_APP_PRIVATE_KEY: ${{ secrets.REACT_APP_PRIVATE_KEY }}
          REACT_APP_CLIENT_EMAIL: ${{ secrets.REACT_APP_CLIENT_EMAIL }}
          REACT_APP_GOOGLESHEET_ID: ${{ secrets.REACT_APP_GOOGLESHEET_ID }}
          REACT_APP_SHEET_ID: ${{ secrets.REACT_APP_SHEET_ID }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
