name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        run: npm install && npm run build

      - name: Upload production-ready build files
        uses: JamesIves/github-pages-deploy-actions@4.1.1
        with:
          name: gh-pages
          path: build
